### ISSUE TITLE
Publishing to IzzyOnDroid repo

### ISSUE THREAD

**Issue by Ounzy** [Ounzy/OpenBl#1]
Bonjour @IzzySoft,
I´ve been using your F-Droid repo for quite a while now and enjoyed finding new apps through it so far.

Now that I've started to get into Android development, I would be very happy to see OpenBl, which is an app for viewing the latest german Bundesliga results and tables, added to your repo.

Greetings Ounzy

**Comment by IzzySoft** [comment]
Hm, on such a special request I can hardly give a straight "No", can I? :see_no_evil: Soccer apps always get me into some special conflict. The category would be "Sports & Health" – and I'm not sure if BuLi (or any other "professional soccer") fits either term :speak_no_evil: but cannot put such an app into "Money" either though that would match best :dash:

OK, let's see:

* shortdesc is too long by 1 char (will be truncated). I'd suggest dropping the trailing "App" (what else would you expect in my repo?)
* will take your fulldesc assuming it's Markdown (looks better). That means it will become a single paragraph, hope that's fine. If not, feel free to make it either Markdown conform (separate paragraphs by empty lines), or use HTML also for `<p>`aragraphs.
* screenshots will be converted to JPG on my end, so no transparency (should the frames look "bad" because of that, consider dropping them :see_no_evil:)

That said, here's your preview from the staging area (before adjusting shortdesc). Will go live with the next sync around 7 pm UTC (unfortunately just missed the last one by an hour):
![image](https://user-images.githubusercontent.com/6781438/222532875-e774ad24-445e-45ef-acee-7c7b8f81414d.png)

**Comment by Ounzy** [comment]
Thank you very much for adding OpenBl to your repo. 
I shortened shortdesc now, so it should be better.

**Comment by IzzySoft** [comment]
77 bytes looks perfectly fine, thanks! Countdown running then: T minus 3.5h now :smile: Once it shows up and you're satisfied, remember you can [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) for e.g. your Readme to link there :smiley:

**Comment by IzzySoft** [comment]
@Ounzy please do not forget to adjust `versionName` and increase `versionCode` when creating a release. The APK at release 2.2 still identifies as `2.0+3` instead of the expected `2.2+5`. My updater just complained this was an old version already existing here :scream:

**Comment by Ounzy** [comment]
> @Ounzy please do not forget to adjust `versionName` and increase `versionCode` when creating a release. The APK at release 2.2 still identifies as `2.0+3` instead of the expected `2.2+5`. My updater just complained this was an old version already existing here 😱
>
Thanks for the catch, that was an accident from my side as I'm still new to it and I'll do my best to not forget bumping `versionCode` and `versionName` ;)
And thank you for keeping an eye on it, great customer support :joy:

**Comment by IzzySoft** [comment]
Well, until you either published a new release or replaced the APK on the currently latest one by a properly versioned, my updater will complain daily – which if it happens too often, might lead to the customer support disabling updates :scream: :dash:
